BG_COLOR = "gray12"
#BG_COLOR_2 = "#1c2c5c"
BG_COLOR_2 = "royal blue"
BG_COLOR_3 = "grey20"
FG_COLOR = "white"
FG_COLOR_2 = "SteelBlue1"
GLOBAL_FONT = ("Calibri", 11, "normal")
BOLD_FONT = ("Calibri", 11, "bold")
BOLD_FONT_2 = ("Calibri", 13, "bold")
